version: '3'
services:      
  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5431:5432
    restart: always
    networks:
      - lahatra3_network

networks:
  lahatra3_network: