CREATE ROLE anonyma nologin;

GRANT USAGE ON SCHEMA public TO anonyma;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anonyma;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anonyma;
